### ISSUE TITLE
Proxy objects

### ISSUE THREAD

**Issue by drekka** [jectivex/JXKit#8]
Hi Marc, sorry for disturbing your weekend.

I've now distilled the code down to this

```swift
let proxyHandler = jsCtx.object()
 try proxyHandler.set("get", convertible: JXValue(newFunctionIn: jsCtx, callback: cacheGet))
try proxyHandler.set("set", convertible: JXValue(newFunctionIn: jsCtx, callback: cacheSet))
try jsCtx.global.setProperty("_cacheProxyHandler", proxyHandler)
try jsCtx.global.setProperty("_cache", jsCtx.object()) // This actually doesn't do anything. We just need a backing object for the proxy.
try jsCtx.eval(#"""
               var cache = new Proxy(_cache, _cacheProxyHandler);
               """#)

private func cacheGet(context: JXContext, object _: JXValue?, args: [JXValue]) throws -> JXValue {
    let key = try args[1].stringValue
    // ... Get and return the JXValue
}

private func cacheSet(context: JXContext, object _: JXValue?, args: [JXValue]) throws -> JXValue {
    let key = try args[1].stringValue
    let value = args[2]
    // ... extract and store the value.
}
```

It's a lot smaller than I had last night because I realised I could move the functions for getting and setting my cache directly to the proxy handler. Last night they were still on the cache object and I was using javascript to call them. So this is looking pretty good. The only real question I guess now is - is it possible to create the `Proxy` without requiring that single line of javascript?

ciao
Derek

**Comment by marcprux** [comment]
You can construct one using a prototype. Something like this:

```swift
let obj = jsCtx.object()
let proxyPrototype = try jsCtx.global["Proxy"]
let proxy = try proxyPrototype.construct(withArguments: [obj, proxyHandler])
```

I've also added some support for creating proxies in [3.2.1](https://github.com/jectivex/JXKit/releases/tag/3.2.1). See the API at https://www.jective.org/JXKit/documentation/jxkit/jxvalue/proxy(get:set:) and sample test cases at https://github.com/jectivex/JXKit/blob/main/Tests/JXKitTests/JXKitTests.swift#L74

**Comment by drekka** [comment]
Nice. I'll update and implement that.

**Comment by drekka** [comment]
Yep. Re-wrote the code to use the `.proxy(...)` function and it's working perfectly. Thanks
